{% set name = "slim-trees" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a5fcc3d1d1f7d021e6304b739f5528983fa01032401a907d374f211a8222ff2d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - numpy
  run_constrained:
    - scikit-learn >=1.1,<1.4
    - lightgbm >=3.2,<4.4

test:
  imports:
    - slim_trees
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Quantco/slim-trees
  summary: A python package for efficient pickling of ML models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
