{% set name = "slim-trees" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slim-trees-{{ version }}.tar.gz
  sha256: 3aad364b52e6354769cabe234d1d76c3006a4dff4063acfc3d658f5522bfe4e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy

test:
  imports:
    - slim_trees
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pavelzw/slim-trees
  summary: A python package for efficient pickling of ML models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
